"""20210731_00:20:47 migration

Revision ID: 9b040ea06803
Revises: 
Create Date: 2021-07-31 00:20:47.695951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b040ea06803'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.Unicode(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('verification_sms_time', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.Unicode(length=255), nullable=True),
    sa.Column('middle_name', sa.Unicode(length=255), nullable=True),
    sa.Column('last_name', sa.Unicode(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=255), nullable=True),
    sa.Column('cover_pic_url', sa.String(length=255), nullable=True),
    sa.Column('document_pic_url', sa.String(length=255), nullable=True),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.Column('reputation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('profile_views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('show_nsfw', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deactivated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_first_log_in', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_birthday_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verified_document', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('show_fullname_instead_of_display_name', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('joined_collaboration', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_user_display_name'), 'user', ['display_name'], unique=True)
    op.create_table('social_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('uid', sa.String(length=200), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_account_user_id'), 'social_account', ['user_id'], unique=False)
    op.create_table('user_ban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ban_by', sa.String(length=255), nullable=True),
    sa.Column('ban_type', sa.Enum('EMAIL', 'PHONE_NUMBER', name='bantypeenum'), server_default='EMAIL', nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ban')
    op.drop_index(op.f('ix_social_account_user_id'), table_name='social_account')
    op.drop_table('social_account')
    op.drop_index(op.f('ix_user_display_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
